// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmgrnkuhprxowcvydnvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtZ3Jua3VocHJ4b3djdnlkbnZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MTc5NDcsImV4cCI6MjA3MjI5Mzk0N30.q2wxy651XYiuQzJny06bL1Xlp337KCD5rBIp-YGQxxQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});